### ISSUE TITLE
Remove ic_launcher.png from library resources

### ISSUE THREAD

**Issue by gabrielemariotti** [jpardogo/GoogleProgressBar#21]
Please remove the ic_launcher.png files from your library.
It is not necessary, and also it is a problem with the last gradle plugin 1.2.x

**Comment by thomasdsouza** [comment]
Thank you for the great library. 
Please consider changing the name of ic_launcher.png files or please remove the ic_launcher.png files from your library.  Libraries that have their own resources (like ActionBarSherlock or Google's own Support v7 library) use distinctive naming schemes to avoid collisions with your resource names (abs_, abc_).

**Comment by jpardogo** [comment]
Yes guys, no problem I will update it asap. I don't know what I was thinking when I left it there. I will try to use prefix for ids and layouts as well. It is long time i don't take a look to the lib I should do an update soon.
